### ISSUE TITLE
Server throws an InvalidProgramException after killing an NPC

### ISSUE THREAD

**Issue by Moneylover3246** [SignatureBeef/Open-Terraria-API#63]
The server throws with this message upon killing an NPC
![image](https://user-images.githubusercontent.com/66443019/156109917-ca19c6db-aa5e-4b03-8777-2e7c2288405f.png)

Tested on commit 50e269a (Windows 10; Terraria v1.4.3.5)

**Comment by SignatureBeef** [comment]
Should be a fix in 85d9d43 / 3.0.33-alpha when it stages through.

**Comment by punchready** [comment]
Sorry for that, i didn't check the `DropLoot` method

**Comment by SignatureBeef** [comment]
All good, it happens and I even missed it.
